### ISSUE TITLE
Lomo Saltado

### ISSUE THREAD

**Issue by Soulfire86** [POSSCON2015/workshop#19]
**Una receta MUY deliciosa!**
Es un plato típico de nuestra gastronomía peruana, que data desde fines del siglo XIX, conocido antes como lomito de vaca o lomito a la chorrillana. Surge por la influencia de los chinos-cantoneses, que fusionado con la sazón peruana, se ha convertido en uno de los platos más consumidos del país.
![lomo_saltado](https://cloud.githubusercontent.com/assets/234468/7161305/75121718-e35c-11e4-8287-ed60c4225bf8.jpg)

Ingredientes
---------------
- 1 kg. de carne de res (bisteck, huachalomo, lomo fino)
- 1/2 kg. cebolla cortada a lo largo (grueso)
- 250 gr. tomate pelado y cortado a lo largo
- 1 kg. papas blanca cortadas para freírlas
- Sal, pimienta y ajos al gusto
- Sillao 
- 3 cucharaditas de perejil picado
- Vinagre
- Aceite vegetal

**Comment by JClapper91** [comment]
-[] Create beverage
-[] Consume beverage
