### ISSUE TITLE
Free food/drink

### ISSUE THREAD

**Issue by eagle79** [POSSCON2015/workshop#24]
- [x] Get food/drink
- [ ] Eat/drink food/drink
- [ ] Let someone else pay for food/drink.

Lather. Rinse. Repeat.

**Comment by phatcabbage** [comment]
Instructions unclear.

I now have a $7000 restaurant bill.

**Comment by eagle79** [comment]
@phatcabbage I guess you're the one paying then? Sounds like another round!

**Comment by eagle79** [comment]
It appears no one wants to pay my bill... go figure. Guess I'll close this one.

**Comment by alexwoehr** [comment]
Aww, man. Bummer.
